image:
    # https://www.appveyor.com/docs/build-environment/#build-worker-images
- Visual Studio 2017
#- Visual Studio 2015

environment:
  OpenCV_DIR: "C:/tools/opencv/build"
  CMAKE_MODULE_PATH: "C:/tools/opencv/build"
  # https://cmake.org/cmake/help/v3.11/generator/Visual%20Studio%2015%202017.html
  #GENERATOR: "Visual Studio 15 2017 Win64"

  #CMAKE_PREFIX_PATH: "C:/tools/opencv/build/OpenCVConfig.cmake"
  #USER:
  #  secure: fXgF9uyy6sT0JoVOR7BoqA==
  #PASS:
  #  secure: 0bXSOVjf9x8L7nErTivu92TF1FwNosTjFJQPmxp8Dys=

  matrix:
    - PYTHON: "C:/Python27"
      GENERATOR: "Visual Studio 15 2017"
      VCVARS_FPATH: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvars32.bat"

    - PYTHON: "C:/Python27-x64"
      GENERATOR: "Visual Studio 15 2017 Win64"
      VCVARS_FPATH: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvars64.bat"

    - PYTHON: "C:/Python34"
      GENERATOR: "Visual Studio 15 2017"

    - PYTHON: "C:/Python34-x64"
      GENERATOR: "Visual Studio 15 2017 Win64"

    - PYTHON: "C:/Python35"
      GENERATOR: "Visual Studio 15 2017"

    - PYTHON: "C:/Python35-x64"
      GENERATOR: "Visual Studio 15 2017 Win64"

    - PYTHON: "C:/Python36"
      GENERATOR: "Visual Studio 15 2017"

    - PYTHON: "C:/Python36-x64"
      GENERATOR: "Visual Studio 15 2017 Win64"

    - PYTHON: "C:/Python37"
      GENERATOR: "Visual Studio 15 2017"

    - PYTHON: "C:/Python37-x64"
      GENERATOR: "Visual Studio 15 2017 Win64"

matrix:
    fast_finish: true

# Reference: https://github.com/votchallenge/trax/blob/master/appveyor.yml
#"%PYTHON%/python.exe" -m pip install ninja
# TODO: try vs15 with ninja
# https://stackoverflow.com/questions/31262342/cmake-g-ninja-on-windows-specify-x64
build_script:
- cmd: |
    call "%VCVARS_FPATH%"
    choco install opencv
    refreshenv
    "%PYTHON%/python.exe" -m pip install --upgrade pip
    "%PYTHON%/python.exe" -m pip install --upgrade setuptools
    "%PYTHON%/python.exe" -m pip install -r requirements.txt
    "%PYTHON%/python.exe" setup.py bdist_wheel -- -G "%GENERATOR%" -DOpenCV_DIR="C:/tools/opencv/build"

before_test:
- ps: |

    cd ${Env:APPVEYOR_BUILD_FOLDER}\tests
    $env:PYTHONWARNINGS = "ignore:::pip._internal.cli.base_command"
    &"${Env:PYTHON}/python.exe" -m pip install --user (ls "../dist/pyhesaff_*.whl")
    if ($LastExitCode -ne 0) {throw $LastExitCode}

test_script:
- cmd: |

    "%PYTHON%/python.exe" -m pip install xdoctest
    "%PYTHON%/python.exe" -m xdoctest -m pyhesaff

artifacts:
- path: dist\*.whl
  name: wheels

deploy_script:
- ps: |

    # TODO: APPVEYOR_REPO_TAG
    if (${Env:APPVEYOR_REPO_TAG} -eq "true") {
      cd ${Env:APPVEYOR_BUILD_FOLDER}
      if (${Env:ENABLE_CONTRIB} -eq 0) {
        if (${Env:ENABLE_HEADLESS} -eq 0) {
          echo "This is a default build. Deployment will be done to PyPI entry opencv-python."
        }
        else {
          echo "This is a headless build. Deployment will be done to PyPI entry opencv-python-headless."
        }
      }
      else {
        if (${Env:ENABLE_HEADLESS} -eq 0) {
          echo "This is a contrib build. Deployment will be done to PyPI entry opencv-contrib-python."
        }
        else {
          echo "This is a headless contrib build. Deployment will be done to PyPI entry opencv-contrib-python-headless."
        }
      }

      &"${Env:PYTHON}/python.exe" -m pip install twine
      &"${Env:PYTHON}/python.exe" -m twine upload -u ${Env:USER} -p ${Env:PASS} --skip-existing dist/opencv*
    }
    else {
      echo "Tag not set, deployment skipped."
    }
