image:
- Visual Studio 2017

environment:
  OpenCV_DIR: "C:/tools/opencv/build"
  CMAKE_MODULE_PATH: "C:/tools/opencv/build"
  #CMAKE_PREFIX_PATH: "C:/tools/opencv/build/OpenCVConfig.cmake"
  #USER:
  #  secure: fXgF9uyy6sT0JoVOR7BoqA==
  #PASS:
  #  secure: 0bXSOVjf9x8L7nErTivu92TF1FwNosTjFJQPmxp8Dys=

  matrix:
    - PYTHON: "C:/Python27"

    - PYTHON: "C:/Python27-x64"

    - PYTHON: "C:/Python34"

    - PYTHON: "C:/Python34-x64"

    - PYTHON: "C:/Python35"

    - PYTHON: "C:/Python35-x64"

    - PYTHON: "C:/Python36"

    - PYTHON: "C:/Python36-x64"

    - PYTHON: "C:/Python37"

    - PYTHON: "C:/Python37-x64"

matrix:
    fast_finish: true

build_script:
- cmd: |
    choco install opencv
    refreshenv
    "%PYTHON%/python.exe" -m pip install --upgrade pip
    "%PYTHON%/python.exe" -m pip install --upgrade setuptools
    "%PYTHON%/python.exe" -m pip install ninja
    "%PYTHON%/python.exe" -m pip install -r requirements.txt
    "%PYTHON%/python.exe" setup.py bdist_wheel -- -DOpenCV_DIR="C:/tools/opencv/build"

before_test:
- ps: |

    cd ${Env:APPVEYOR_BUILD_FOLDER}\tests
    $env:PYTHONWARNINGS = "ignore:::pip._internal.cli.base_command"
    &"${Env:PYTHON}/python.exe" -m pip install --user (ls "../dist/pyhesaff_*.whl")
    if ($LastExitCode -ne 0) {throw $LastExitCode}

test_script:
- cmd: |

    "%PYTHON%/python.exe" -m pip install xdoctest
    "%PYTHON%/python.exe" -m xdoctest -m pyhesaff

artifacts:
- path: dist\*.whl
  name: wheels

deploy_script:
- ps: |

    # TODO: APPVEYOR_REPO_TAG
    if (${Env:APPVEYOR_REPO_TAG} -eq "true") {
      cd ${Env:APPVEYOR_BUILD_FOLDER}
      if (${Env:ENABLE_CONTRIB} -eq 0) {
        if (${Env:ENABLE_HEADLESS} -eq 0) {
          echo "This is a default build. Deployment will be done to PyPI entry opencv-python."
        }
        else {
          echo "This is a headless build. Deployment will be done to PyPI entry opencv-python-headless."
        }
      }
      else {
        if (${Env:ENABLE_HEADLESS} -eq 0) {
          echo "This is a contrib build. Deployment will be done to PyPI entry opencv-contrib-python."
        }
        else {
          echo "This is a headless contrib build. Deployment will be done to PyPI entry opencv-contrib-python-headless."
        }
      }

      &"${Env:PYTHON}/python.exe" -m pip install twine
      &"${Env:PYTHON}/python.exe" -m twine upload -u ${Env:USER} -p ${Env:PASS} --skip-existing dist/opencv*
    }
    else {
      echo "Tag not set, deployment skipped."
    }
